Repository rubyconfig/config, pull requests merged in 2020-01, with the labels that each got.

#247 Config doesn't have to be a Rails Engine
  CHANGELOG.md
  lib/config.rb
  lib/config/integrations/rails/engine.rb
Labels: improvement

#263 Cleanup example Rails application used for testing
  .gitignore
  CHANGELOG.md
  spec/app/rails_5.0/.gitignore
  spec/app/rails_5.1/.gitignore
  spec/app/rails_5.1/Gemfile
  spec/app/rails_5.2/.gitignore
  spec/app/rails_5.2/.ruby-version
  spec/app/rails_5.2/Gemfile
Labels: improvement

#253 Require dry-validation only when schema is specified
  CHANGELOG.md
  lib/config.rb
  lib/config/validation/schema.rb
  spec/validation_spec.rb
Labels: improvement

#265 Upgrade markdown linter and fix documentation errors
  .mdlstyle.rb
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  config.gemspec
Labels: documentation

#255 Fix missing new_ostruct_member in Ruby 2.7
  .travis.yml
  CHANGELOG.md
  lib/config/options.rb
Labels: bug

#264 Upgrade development dependencies and test matrix with latest Ruby and Rails versions
  .travis.yml
  Appraisals
  CHANGELOG.md
  config.gemspec
  gemfiles/rails_4.2.gemfile
  gemfiles/rails_5.0.gemfile
  gemfiles/rails_5.1.gemfile
  gemfiles/rails_5.2.gemfile
  gemfiles/sinatra.gemfile
Labels: improvement

#260 Fix validation contract documentation
  CHANGELOG.md
  README.md
Labels: bug, documentation

#250 Defer modification of ActionController::Base to when it is loaded
  CHANGELOG.md
  lib/config/integrations/rails/railtie.rb
Labels: improvement

#266 Replace Travis CI with GitHub Actions
  .editorconfig
  .github/workflows/tests.yml
  .travis.yml
  Appraisals
  CHANGELOG.md
  README.md
  Rakefile
  config.gemspec
  spec/spec_helper.rb
Labels: improvement

#267 Excluded test application's *.md files from the gem build
  .rubocop.yml
  CHANGELOG.md
  config.gemspec
Labels: bug

#268 Rename GitHub organization name from `railsconfig` to `rubyconfig`
  CHANGELOG.md
  README.md
  config.gemspec
Labels: documentation
