Repository rubyconfig/config, pull requests merged in 2020-06, with the labels that each got.

#278 Fix failing build and upgrade dev dependencies
  .github/workflows/tests.yml
  Appraisals
  config.gemspec
Labels: bug

#277 Added alias to_h for to_hash
  CHANGELOG.md
  lib/config/options.rb
  spec/config_spec.rb
Labels: feature

#280 Fix broken link to LICENSE.md
  README.md
Labels: documentation
