Repository rubyconfig/config, pull requests merged in 2020-12, with the labels that each got.

#292 Add explicit implementation of Config::Options#as_json
  CHANGELOG.md
  lib/config/options.rb
  spec/options_spec.rb
Labels: bug

#293 Raise explicit error on env var conflicts
  CHANGELOG.md
  README.md
  lib/config/options.rb
  spec/config_env_spec.rb
Labels: bug, feature

#295 Revert "Added alias to_h for to_hash (#277)"
  CHANGELOG.md
  lib/config/options.rb
  spec/config_spec.rb
Labels: bug

#297 Added alias to_h for to_hash
  CHANGELOG.md
  lib/config/options.rb
  spec/config_spec.rb
Labels: bug

#296 Additional tests for parsing values
  spec/fixtures/settings.yml
  spec/options_spec.rb
Labels: documentation

#298 Run examples in random order
  .rspec
  spec/config_env_spec.rb
  spec/config_spec.rb
  spec/options_spec.rb
  spec/spec_helper.rb
Labels: improvement
